### ISSUE TITLE
Linking to openssl 1.1 on Debian not working

### ISSUE THREAD

**Issue by rubak** [spatstat/s2#2]
The package doesn't compile on Debian with openssl 1.1 which can be tested with `rhub::check` (with the root of the `s2` package as current working directory):

    rhub::check(platform = "debian-gcc-devel")

The problem arises when exactfloat.cc is compiled

```
g++ -std=gnu++11 -I/opt/R-devel/lib/R/include -DNDEBUG -DS2_USE_EXACTFLOAT -DHASH_NAMESPACE=std -DNDEBUG -I./geometry -I./geometry/s2 -I/usr/local/include -I"/home/docker/R/Rcpp/include"  -pthread -fpic  -Wall -pedantic -c geometry/util/math/exactfloat/exactfloat.cc -o geometry/util/math/exactfloat/exactfloat.o
In file included from geometry/util/math/exactfloat/exactfloat.cc:3:0:
./geometry/util/math/exactfloat/exactfloat.h:502:10: error: field ‘bn_’ has incomplete type ‘BIGNUM {aka bignum_st}’
   BIGNUM bn_;
          ^~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./geometry/util/math/exactfloat/exactfloat.h:108,
                 from geometry/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from geometry/util/math/exactfloat/exactfloat.cc:3:0:
./geometry/util/math/exactfloat/exactfloat.h: In constructor ‘ExactFloat::ExactFloat()’:
./geometry/util/math/exactfloat/exactfloat.h:562:15: error: ‘BN_init’ was not declared in this scope
   BN_init(&bn_);
               ^
geometry/util/math/exactfloat/exactfloat.cc: In function ‘int BN_ext_count_low_zero_bits(const BIGNUM*)’:
geometry/util/math/exactfloat/exactfloat.cc:75:25: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
   for (int i = 0; i < bn->top; ++i) {
                         ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./geometry/util/math/exactfloat/exactfloat.h:108,
                 from geometry/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
geometry/util/math/exactfloat/exactfloat.cc:76:20: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
     BN_ULONG w = bn->d[i];
                    ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./geometry/util/math/exactfloat/exactfloat.h:108,
                 from geometry/util/math/exactfloat/exactfloat.cc:3:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
geometry/util/math/exactfloat/exactfloat.cc: In constructor ‘ExactFloat::ExactFloat(double)’:
geometry/util/math/exactfloat/exactfloat.cc:90:15: error: ‘BN_init’ was not declared in this scope
   BN_init(&bn_);
               ^
geometry/util/math/exactfloat/exactfloat.cc: In constructor ‘ExactFloat::ExactFloat(int)’:
geometry/util/math/exactfloat/exactfloat.cc:113:15: error: ‘BN_init’ was not declared in this scope
   BN_init(&bn_);
               ^
geometry/util/math/exactfloat/exactfloat.cc: In copy constructor ‘ExactFloat::ExactFloat(const ExactFloat&)’:
geometry/util/math/exactfloat/exactfloat.cc:125:15: error: ‘BN_init’ was not declared in this scope
   BN_init(&bn_);
               ^
```

**Comment by edzer** [comment]
The [cran results page](https://cran.r-project.org/web/checks/check_results_s2.html) shows three errors now, two of them on fedora 26; both seem related to some BIGNUM type not defined.

**Comment by rubak** [comment]
Looks like this is getting more critical as systems upgrade to OpenSSL 1.1. I'm not proficient enough with C++ to solve it easily/quickly, so if we could find somebody to help with this it would be great.

I think the problem comes from the fact that `BN_init` was removed from OpenSSL as described here: https://wiki.openssl.org/index.php/Manual:BN_new(3)#REMOVED_FUNCTIONALITY

**Comment by rubak** [comment]
OK. After reading up on RAII (resource acquisition is initialization) and using [this simple example](https://isocpp.org/wiki/faq/exceptions#finally) as a template I might have solved this problem. I have made a `openssl_1.1.0` branch in [our copy of the upstream sources](https://github.com/spatstat/s2-geometry-library) and it passed all the tests running there (still on OpenSSL 1.0). Next step is to see how the new code copes with OpenSSL 1.1, but theoretically it should be fine since I have removed all instances of BN_init (I believe). Fingers crossed :-)

**Comment by rubak** [comment]
Well, that didn't solve the problem :-( At least I got a new error:

```
g++ -std=gnu++11 -I/opt/R-patched/lib64/R/include -DNDEBUG -DS2_USE_EXACTFLOAT -DHASH_NAMESPACE=std -I../inst/include -I../inst/include/s2 -I../inst/include/base -I../inst/include/strings -I../inst/include/util/hash -I"/home/docker/R/Rcpp/include" -I/usr/local/include -pthread -fpic -Wall -pedantic -c geometry/util/math/exactfloat/exactfloat.cc -o geometry/util/math/exactfloat/exactfloat.o

geometry/util/math/exactfloat/exactfloat.cc: In function ‘int BN_ext_count_low_zero_bits(const BIGNUM*)’:

geometry/util/math/exactfloat/exactfloat.cc:75:25: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
```

**Comment by edzer** [comment]
@jeroen , are you familiar with packages with C++ code linking to OpenSSL, and these version issues?

**Comment by jeroen** [comment]
Haven't looked closely at your code, but openssl 1.1 has changed the API a bit. Most of the pointers to internal struct fields have been replaced with proper get/set functions. 

Have a look at [compatibility.c](https://github.com/jeroen/openssl/blob/master/src/compatibility.c) and [compatibility.h](https://github.com/jeroen/openssl/blob/master/src/compatibility.h) in the openssl package.

**Comment by jeroen** [comment]
By the way if you're on OSX you can easily test this using `brew install openssl@1.1`

**Comment by rubak** [comment]
Looks like @jeroen is pointing in the right direction: The error occurs when we try to access the internal fields `top` or `d` in a BIGNUM. There are only two functions where the problem occurs:

- [BN_ext_get_uint64](https://github.com/spatstat/s2/blob/c3b072a9393c0edc2ad241d4e9e62fbd07c25656/src/geometry/util/math/exactfloat/exactfloat.cc#L58)
- [BN_ext_count_low_zero_bits](https://github.com/spatstat/s2/blob/c3b072a9393c0edc2ad241d4e9e62fbd07c25656/src/geometry/util/math/exactfloat/exactfloat.cc#L73)

However, there doesn't seem to be get functions for these fields (they may be too implementation specific for them to be part of the API). I will ask on SO and see if somebody can give me hints of how to implement these differently.

I have tried to replace these by dummy functions and the library compiles fine with OpenSSL 1.1.0 once we get rid of `->top` and `->d`.

**Comment by jeroen** [comment]
@rubak have a look at how I do this in the openssl package: https://github.com/jeroen/openssl/blob/master/src/bignum.c#L52-L56. 

You can use integer division `BN_div_word ` or `BN_mod_word ` to break down your BIGNUM in `BN_ULONG` fraction and `BN_ULONG` modulo. From there you can reconstruct your integer.

**Comment by rubak** [comment]
Thanks again @jeroen for pointing me in a good direction. If we assume there's a 32 bit word length in my `BIGNUM`s and I have 2^64-1 represented as a BIGNUM `x`. Then I can try to divide `x` by the maximal word 2^32-1 which would give the unrepresentable number 2^32+1. In general I guess I can only recover `BIGNUM`s of size ~2^64 with 32 bit words and ~2^128 with 64 bit words or am I missing something here?

**Comment by rubak** [comment]
Anyway, after digging a bit more if found that some bitwise operations are directly available in OpenSSL and at least for `BN_ext_count_low_zero_bits` I think it is very easy to use `BN_is_bit_set` in a while loop to do this calculation. I wonder why this was not done originally, but there might be some speed difference...
